### PR TITLE
Use Simplenote API version 2 and asynchronous server access

### PR DESCRIPTION
**Pull request by alpha22jp**
Hello @dotemacs 

I'm now rewriting simplenote.el in this branch. The points of this branch are
- Use [Simplenote API version 2](http://kendersec.github.io/SimpleNote/SimpleNote-API-v2.1.3.pdf) to support tags, automatic merge and some ohter functions.
- Asynchronous server access using [request-deferred.el](http://melpa.org/#/request-deferred).

But as you can see from the diff, I've already changed a large portion of codes from the original. So I think it's better to make this a different package named simplenote2.el (because it uses API ver.2 :smiley:) instead of asking you to merge it.

What do you think of it?

### CODE REVIEW

**Comment by dotemacs** [comment]
Hello @alpha22jp 

wow, very impressive! :) 

Considering how much work you've done it would be crazy to discourage you from further work.

It's great that you've found the API v2 docs, cos I've dug them up myself previously, but never managed to get around to implement the code for it. What is crazy in my opinion is that Simperium, the company, was initially supportive of people implementing clients in various languages, but then they just stopped to care.

Options:

1. So if you want to merge this into simplenote.el and announce that v1 of the API won't be supported any longer, fine with me

1. If you want to create a new package, as mentioned, simplenote2.el, also good with me. If you decide to go with this option, I'll just mention in the README that simplenote2.el should be used instead, as it'll have more features.

1. If you want to get access to this repo, considering how much you've contributed, also good with me

The decision is up to you, let me know what you feel most comfortable with.

Thanks
Alex

**Comment by alpha22jp** [comment]
Hello @dotemacs,

Thanks for your quick response.

> It's great that you've found the API v2 docs, cos I've dug them up myself previously, but never managed to get around to implement the code for it. What is crazy in my opinion is that Simperium, the company, was initially supportive of people implementing clients in various languages, but then they just stopped to care.

Yes, I just happened to find that document while I was browsing. :smiley: As you said, I can't find the same one anywhere on Simperium web site. It might be the one someone put personally. But [simplenote.py](https://github.com/mrtazz/simplenote.py) appears to have been using API ver.2 since it was initially released on June 2011 according to the commit log. So I think it was available around that time, but Simperium stopped providing it after that.

Anyway, I'd like to release the new version of simplenote.el as a different package. I believe it's useful for most users, but some users may not want those new features. I created the repository for simplenote2.el [here](https://github.com/alpha22jp/simplenote2.el). I need some more work to do, but it's almost working fine. I would appriciate if you make a link to this repository in the README of simplenote.el.

Thanks.

**Comment by dotemacs** [comment]
Great work. 

I've created a PR in MELPA for it, see: https://github.com/milkypostman/melpa/pull/2507

**Comment by dotemacs** [comment]
Hello @alpha22jp 

posting a new comment, just so that you don't miss it, see the PR here and the comments:

https://github.com/milkypostman/melpa/pull/2507

Thanks

**Comment by alpha22jp** [comment]
Hello @dotemacs 
I close this pull request.

**Comment by dotemacs** [comment]
Fine, thank you :smile:

**Pull request closed without merging**
